services:
  backend:
    build: ./backend
    container_name: url_shortner_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/url-shortner
    depends_on:
      - mongo

  frontend:
    build: ./frontend/vite-project  
    container_name: url_shortner_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: url_shortner_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
